import Head from 'next/head'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Lines from '../components/Lines'
import Main from '../components/Main'

export default function Home() {
  return (
    <div>
      <Head>
        <title>sana.moda</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Oswald:wght@200;300;400;500;600;700&display=swap" rel="stylesheet" />
      </Head>
    {/*  h-screen scrollbar-thin scrollbar-thumb-theme scrollbar-track-[#272727]    bg-[#DFDFDF]*/}
      <main className="font-mont bg-[#FFF] h-screen scrollbar-thin scrollbar-thumb-theme ">
        <Lines />
        <Header />
        <Main />
        <Footer />
      </main>
    </div>
  )
}
